---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: elite

workflows:
  primary:
    steps:
    - script@1:
        title: "🚀 Initialize Windows RDP System"
        inputs:
        - content: |
            #!/bin/bash
            set -e
            
            echo ""
            echo "╔═══════════════════════════════════════════════════════════════════════╗"
            echo "║                                                                       ║"
            echo "║        🖥️  WINDOWS 11 REMOTE DESKTOP - INITIALIZING                  ║"
            echo "║                                                                       ║"
            echo "╚═══════════════════════════════════════════════════════════════════════╝"
            echo ""
            
            # [1/4] Create Docker Compose
            echo "[1/4] 🐳 Creating Docker configuration..."
            cat <<EOF > docker-compose.yml
            version: "3.9"
            services:
              windows:
                image: dockurr/windows
                container_name: windows_rdp
                privileged: true
                environment:
                  VERSION: "11"
                  USERNAME: "Zun"
                  PASSWORD: "123456"
                  RAM_SIZE: "28G"
                  CPU_CORES: "8"
                  DISK_SIZE: "100G"
                  KVM: "Y"
                devices:
                  - /dev/kvm:/dev/kvm
                cap_add:
                  - NET_ADMIN
                  - SYS_ADMIN
                security_opt:
                  - apparmor:unconfined
                  - seccomp:unconfined
                ports:
                  - "8006:8006"
                  - "3389:3389/tcp"
                  - "3389:3389/udp"
                  - "5900:5900"
                volumes:
                  - ./storage:/storage
                restart: always
                stop_grace_period: 2m
            EOF
            echo "      ✅ Docker Compose created"
            
            # [2/4] Start Docker Container
            echo "[2/4] 🚀 Starting Windows 11 container..."
            docker compose up -d > /dev/null 2>&1
            echo "      ✅ Container started successfully"
            
            # [3/4] Download Kami Tunnel
            echo "[3/4] 📥 Downloading Kami Tunnel..."
            wget -q https://github.com/kami2k1/tunnel/releases/latest/download/kami-tunnel-linux-amd64.tar.gz
            tar -xzf kami-tunnel-linux-amd64.tar.gz > /dev/null 2>&1
            chmod +x kami-tunnel
            echo "      ✅ Kami Tunnel ready"
            
            # [4/4] Start Tunnels
            echo "[4/4] 🌐 Starting tunnel services..."
            
            # Tunnel cho RDP (3389)
            nohup ./kami-tunnel 3389 > tunnel_rdp.log 2>&1 &
            RDP_PID=$!
            echo "      ✅ RDP Tunnel started (PID: $RDP_PID)"
            
            sleep 2
            
            # Tunnel cho Web Viewer (8006)
            nohup ./kami-tunnel 8006 > tunnel_web.log 2>&1 &
            WEB_PID=$!
            echo "      ✅ Web Viewer Tunnel started (PID: $WEB_PID)"
            
            sleep 2
            
            # Tunnel cho VNC (5900)
            nohup ./kami-tunnel 5900 > tunnel_vnc.log 2>&1 &
            VNC_PID=$!
            echo "      ✅ VNC Tunnel started (PID: $VNC_PID)"
            
            echo ""
            echo "═══════════════════════════════════════════════════════════════════════"
            echo "  ✅ All services started successfully!"
            echo "═══════════════════════════════════════════════════════════════════════"
            echo ""

    - script@1:
        title: "🌐 Get Connection Information"
        inputs:
        - content: |
            #!/bin/bash
            
            echo ""
            echo "🔄 Establishing tunnel connections..."
            echo ""
            
            # ===== Lấy IP cho RDP (Port 3389) =====
            echo "⏳ [1/3] Waiting for RDP tunnel (Port 3389)..."
            RDP_IP=""
            RETRY=0
            
            while [ -z "$RDP_IP" ] && [ $RETRY -lt 60 ]; do
              if [ -f kami_tunnel.txt ]; then
                # Đọc IP từ file, lọc bỏ IP server Bitrise (103.78.x.x)
                TEMP_IP=$(cat kami_tunnel.txt 2>/dev/null | grep -v "103.78" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+' | head -1)
                if [ -n "$TEMP_IP" ]; then
                  # LƯU VÀO BIẾN RDP_IP
                  RDP_IP="$TEMP_IP"
                  echo "      ✅ RDP: $RDP_IP"
                  # XÓA FILE để tunnel tiếp theo có thể ghi vào
                  rm -f kami_tunnel.txt
                  break
                fi
              fi
              sleep 1
              RETRY=$((RETRY + 1))
            done
            
            if [ -z "$RDP_IP" ]; then
              echo "      ❌ ERROR: RDP tunnel failed"
              RDP_IP="Failed"
            fi
            
            # Chờ 3 giây cho tunnel Web ghi IP vào file mới
            echo "      ⏳ Waiting 3s for next tunnel..."
            sleep 3
            
            # ===== Lấy IP cho Web Viewer (Port 8006) =====
            echo "⏳ [2/3] Waiting for Web Viewer tunnel (Port 8006)..."
            WEB_IP=""
            RETRY=0
            
            while [ -z "$WEB_IP" ] && [ $RETRY -lt 60 ]; do
              if [ -f kami_tunnel.txt ]; then
                # Đọc IP từ file, lọc bỏ IP server Bitrise
                TEMP_IP=$(cat kami_tunnel.txt 2>/dev/null | grep -v "103.78" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+' | head -1)
                if [ -n "$TEMP_IP" ]; then
                  # LƯU VÀO BIẾN WEB_IP
                  WEB_IP="$TEMP_IP"
                  echo "      ✅ Web: $WEB_IP"
                  # XÓA FILE để tunnel tiếp theo có thể ghi vào
                  rm -f kami_tunnel.txt
                  break
                fi
              fi
              sleep 1
              RETRY=$((RETRY + 1))
            done
            
            if [ -z "$WEB_IP" ]; then
              echo "      ⚠️  Web Viewer tunnel not available"
              WEB_IP="N/A"
            fi
            
            # Chờ 3 giây cho tunnel VNC ghi IP vào file mới
            echo "      ⏳ Waiting 3s for next tunnel..."
            sleep 3
            
            # ===== Lấy IP cho VNC (Port 5900) =====
            echo "⏳ [3/3] Waiting for VNC tunnel (Port 5900)..."
            VNC_IP=""
            RETRY=0
            
            while [ -z "$VNC_IP" ] && [ $RETRY -lt 60 ]; do
              if [ -f kami_tunnel.txt ]; then
                # Đọc IP từ file, lọc bỏ IP server Bitrise
                TEMP_IP=$(cat kami_tunnel.txt 2>/dev/null | grep -v "103.78" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+' | head -1)
                if [ -n "$TEMP_IP" ]; then
                  # LƯU VÀO BIẾN VNC_IP
                  VNC_IP="$TEMP_IP"
                  echo "      ✅ VNC: $VNC_IP"
                  # Không cần xóa vì đây là tunnel cuối cùng
                  break
                fi
              fi
              sleep 1
              RETRY=$((RETRY + 1))
            done
            
            if [ -z "$VNC_IP" ]; then
              echo "      ⚠️  VNC tunnel not available"
              VNC_IP="N/A"
            fi
            
            echo ""
            echo "✅ All IPs collected!"
            echo "   RDP: $RDP_IP"
            echo "   Web: $WEB_IP"
            echo "   VNC: $VNC_IP"
            
            # ===== Hiển thị thông tin - DỄ COPY =====
            echo ""
            echo ""
            echo "╔═══════════════════════════════════════════════════════════════════════╗"
            echo "║              ✅ WINDOWS 11 PROFESSIONAL - READY                       ║"
            echo "╚═══════════════════════════════════════════════════════════════════════╝"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "🔌 REMOTE DESKTOP (RDP)"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "IP:       $RDP_IP"
            echo "Username: Zun"
            echo "Password: 123456"
            echo "Port:     3389"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "🌐 WEB VIEWER"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "URL:      http://$WEB_IP"
            echo "Port:     8006"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "🖥️  VNC VIEWER"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "IP:       $VNC_IP"
            echo "Port:     5900"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "💻 SYSTEM SPECS"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "CPU:      8 vCPU"
            echo "RAM:      28GB"
            echo "Storage:  100GB"
            echo ""
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "💡 Copy IP addresses above!"
            echo ""
            
            # Lưu vào environment
            envman add --key RDP_IP --value "$RDP_IP"
            envman add --key WEB_IP --value "$WEB_IP"
            envman add --key VNC_IP --value "$VNC_IP"

    - script@1:
        title: "⏰ Maintain Active Session"
        inputs:
        - content: |
            #!/bin/bash
            
            echo ""
            echo "🟢 Windows 11 running..."
            echo ""
            
            echo "═══════════════════════════════════════════════════════════════════════"
            echo "  📋 DOCKER STATUS"
            echo "═══════════════════════════════════════════════════════════════════════"
            docker ps --format "table {{.Names}}\t{{.Status}}"
            echo "═══════════════════════════════════════════════════════════════════════"
            echo ""
            
            COUNTER=0
            while true; do
              ELAPSED=$((COUNTER * 5))
              
              if [ $((COUNTER % 6)) -eq 0 ]; then
                echo ""
                echo "═══════════════════════════════════════════════════════════════════"
                echo "  🖥️  WINDOWS 11 - STATUS"
                echo "═══════════════════════════════════════════════════════════════════"
                echo "  📅 Time      : $(date +'%Y-%m-%d %H:%M:%S')"
                echo "  ⏱️  Uptime    : ${ELAPSED} min"
                echo "  🌐 RDP       : $RDP_IP"
                echo "  🌐 Web       : http://$WEB_IP"
                echo "  🖥️  VNC       : $VNC_IP"
                echo "  🟢 Status    : ACTIVE"
                echo "═══════════════════════════════════════════════════════════════════"
                echo ""
              fi
              
              echo -ne "  🟢 Active | ⏱️  ${ELAPSED} min\r"
              sleep 300
              COUNTER=$((COUNTER + 1))
            done

triggers:
  push:
    branch: main
  pull_request:
    source_branch: "*"
